services:
  postgres_db:
    image: postgres:16-alpine # Using a lightweight PostgreSQL image
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: envirosense     # The database name
      POSTGRES_USER: dummy_user       # The database user
      POSTGRES_PASSWORD: dummy_password # The database password
      PGDATA: /var/lib/postgresql/data/pgdata # Specifies the data directory within the container
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data to a named volume
    ports:
      - "5432:5432" # Map container port 5432 to host port 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dummy_user -d mydummy_database"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # Named volume for PostgreSQL data persistence
