version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: envirosense
      POSTGRES_USER: dummy_user
      POSTGRES_PASSWORD: dummy_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dummy_user -d envirosense"]
      interval: 5s
      timeout: 5s
      retries: 5

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    restart: unless-stopped
    ports:
      - "5000:80"    
      - "2525:25"    
    volumes:
      - smtp4dev-data:/smtp4dev

volumes:
  postgres_data:
  smtp4dev-data:
