version: '3.8'

services:
  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - "5000:80"
      - "2525:25"
    restart: unless-stopped
    volumes:
      - smtp4dev-data:/smtp4dev

volumes:
  smtp4dev-data:
